In [30]:
import pandas as pd

In [31]:
arquivo = pd.read_excel(r'..\exports\dados_exportados_jira.xlsx')
arquivo_ano = pd.read_excel(r'..\exports\dados_exportados_jira_por_ano.xlsx')

In [32]:
arquivo.columns.tolist()

['META_ID',
 'Chave',
 'Resumo',
 '% de Cumprimento',
 'Afeta as versões',
 'Ano da Meta',
 'Cargo do Gerente Responsável',
 'Componentes',
 'Criador',
 'Data da Aprovação pelo Comitê de Governança e Gestão Estratégica',
 'Data da Entrega do Formulário',
 'Data de Apuração',
 'Dirigência Responsável',
 'E-mail do Gerente Responsável',
 'E-mail do Responsável pelo Preenchimento',
 'Estado',
 'Etiquetas',
 'Fim Efetivo',
 'Fim Previsto',
 'Fonte da Informação',
 'Forma de apuração do resultado final',
 'Fórmula de Cálculo',
 'Gerente Responsável',
 'Indicador Estratégico',
 'Informação complementar',
 'Iniciativas Estratégicas 2025',
 'Início Efetivo',
 'Início Previsto',
 'Macrodesafio',
 'Meta_apuração',
 'Nome do Responsável pelo Preenchimento',
 'Nº_Meta',
 'Objetivo de Desenvolvimento Sustentável (ODS)',
 'Outras Unidades Envolvidas',
 'Patrocinador',
 'Periodicidade',
 'Planos Institucionais',
 'Polaridade',
 'Principal',
 'Prioridade',
 'Projeto',
 'Resolução',
 'Responsável',
 'Subtarefas',
 'Telefone do Gerente Responsável',
 'Tipo de Meta',
 'Unidade Gestora',
 'Unidade de Medida',
 'Valor Apurado',
 'Valor da Meta',
 'Versões de correção',
 'Votos']

In [33]:
arquivo_ano['Unidade Gestora'].unique().tolist()

['COINJ',
 'COASSED',
 'SEGOVE',
 'DIRTEC',
 'DIRFIN',
 'DIRDEP',
 'ASPREC',
 'SEPAD',
 'DIRSUP',
 'DIRSEP',
 'DENGEP',
 'DIRGED',
 'SEPLAN',
 'Programa Novos Rumos - GMF',
 'Presidência',
 'Superintendência da Gestão de Inovação',
 'Superintendência Judiciária',
 'DIRCOR',
 'Núcleo de Voluntariado',
 'COMSIV',
 'COSIP',
 'GMF',
 'CEGINP',
 'CEPROC',
 'NUGIN',
 'GMF - PAI PJ',
 'GMF - APAC',
 'CESUS',
 '2ª Vice Presidência']

In [34]:
arquivo_ano = pd.read_excel(r'..\exports\dados_exportados_jira_por_ano.xlsx')
df_extracao_ano = arquivo_ano[['Resumo', 'Ano da Meta']].copy()
df_extracao_ano['Meta'] = df_extracao_ano['Resumo'].str.extract(r'(TJMG\s+\d+)')[0].str.strip()
df_extracao_ano = df_extracao_ano[['Meta', 'Ano da Meta']].copy()
df_extracao_ano = df_extracao_ano[df_extracao_ano['Ano da Meta'] == 2025].copy()
metas_ano_final = df_extracao_ano['Meta'].unique().tolist()
metas_ano_final

['TJMG 154',
 'TJMG 153',
 'TJMG 152',
 'TJMG 151',
 'TJMG 150',
 'TJMG 129',
 'TJMG 155',
 'TJMG 156',
 'TJMG 137',
 'TJMG 69',
 'TJMG 104',
 'TJMG 67',
 'TJMG 136',
 'TJMG 126',
 'TJMG 123',
 'TJMG 109',
 'TJMG 96',
 'TJMG 95',
 'TJMG 62',
 'TJMG 40',
 'TJMG 135',
 'TJMG 134',
 'TJMG 59',
 'TJMG 29',
 'TJMG 140',
 'TJMG 139',
 'TJMG 138',
 'TJMG 97',
 'TJMG 149',
 'TJMG 148',
 'TJMG 147',
 'TJMG 146',
 'TJMG 142',
 'TJMG 141',
 'TJMG 133',
 'TJMG 132',
 'TJMG 130',
 'TJMG 128',
 'TJMG 115',
 'TJMG 91',
 'TJMG 85',
 'TJMG 80',
 'TJMG 79',
 'TJMG 17',
 'TJMG 10',
 'TJMG 7',
 'TJMG 6',
 'TJMG 5',
 'TJMG 100',
 'TJMG 131',
 'TJMG 145',
 'TJMG 144',
 'TJMG 143',
 'TJMG 124',
 'TJMG 111']

In [35]:
metas_ano = pd.read_excel(r'..\exports\dados_detalhados_metas_2025.xlsx')
metas_ano_proc = metas_ano[['META_ID', 'Chave','Resumo', 'Nº_Meta', 'Data de Apuração', 'Ano da Meta', 'Valor da Meta', 'Valor Apurado']].copy()
metas_ano_proc['Meta'] = metas_ano_proc['Resumo'].str.extract(r'(TJMG\s+\d+)')[0].str.strip()
metas_ano_proc = metas_ano_proc[['Meta', 'Chave', 'Nº_Meta', 'Ano da Meta', 'Data de Apuração', 'Valor da Meta', 'Valor Apurado']].copy()
metas_ano_proc['Chave'].tolist()

['ASPLAGMETA-2871',
 'ASPLAGMETA-2857',
 'ASPLAGMETA-2843',
 'ASPLAGMETA-2829',
 'ASPLAGMETA-2815',
 'ASPLAGMETA-2129',
 'ASPLAGMETA-2801',
 'ASPLAGMETA-2137',
 'ASPLAGMETA-2787',
 'ASPLAGMETA-2773',
 'ASPLAGMETA-2142',
 'ASPLAGMETA-2141',
 'ASPLAGMETA-1346',
 'ASPLAGMETA-109',
 'ASPLAGMETA-107',
 'ASPLAGMETA-2140',
 'ASPLAGMETA-1855',
 'ASPLAGMETA-986',
 'ASPLAGMETA-2139',
 'ASPLAGMETA-1190',
 'ASPLAGMETA-107',
 'ASPLAGMETA-64',
 'ASPLAGMETA-2138',
 'ASPLAGMETA-2136',
 'ASPLAGMETA-2081',
 'ASPLAGMETA-2135',
 'ASPLAGMETA-1700',
 'ASPLAGMETA-2134',
 'ASPLAGMETA-1204',
 'ASPLAGMETA-2133',
 'ASPLAGMETA-1841',
 'ASPLAGMETA-103',
 'ASPLAGMETA-2132',
 'ASPLAGMETA-2111',
 'ASPLAGMETA-2110',
 'ASPLAGMETA-2104',
 'ASPLAGMETA-1940',
 'ASPLAGMETA-1827',
 'ASPLAGMETA-1785',
 'ASPLAGMETA-1756',
 'ASPLAGMETA-1728',
 'ASPLAGMETA-1433',
 'ASPLAGMETA-1374',
 'ASPLAGMETA-111',
 'ASPLAGMETA-102',
 'ASPLAGMETA-79',
 'ASPLAGMETA-78',
 'ASPLAGMETA-76',
 'ASPLAGMETA-75',
 'ASPLAGMETA-57',
 'ASPLAGMETA-2131',
 'ASPLAGMETA-1162',
 'ASPLAGMETA-97',
 'ASPLAGMETA-2142',
 'ASPLAGMETA-2130',
 'ASPLAGMETA-2112',
 'ASPLAGMETA-1742',
 'ASPLAGMETA-1488',
 'ASPLAGMETA-93',
 'ASPLAGMETA-59',
 'ASPLAGMETA-2129',
 'ASPLAGMETA-2128',
 'ASPLAGMETA-2127',
 'ASPLAGMETA-2053',
 'ASPLAGMETA-1558',
 'ASPLAGMETA-90',
 'ASPLAGMETA-2126',
 'ASPLAGMETA-1588',
 'ASPLAGMETA-88',
 'ASPLAGMETA-2125',
 'ASPLAGMETA-2124',
 'ASPLAGMETA-2123',
 'ASPLAGMETA-2122',
 'ASPLAGMETA-1220',
 'ASPLAGMETA-86',
 'ASPLAGMETA-2121',
 'ASPLAGMETA-2120',
 'ASPLAGMETA-2119',
 'ASPLAGMETA-2118',
 'ASPLAGMETA-2117',
 'ASPLAGMETA-2116',
 'ASPLAGMETA-2115',
 'ASPLAGMETA-2114',
 'ASPLAGMETA-2113',
 'ASPLAGMETA-2112',
 'ASPLAGMETA-2111',
 'ASPLAGMETA-1940',
 'ASPLAGMETA-2110',
 'ASPLAGMETA-1785',
 'ASPLAGMETA-78',
 'ASPLAGMETA-2127',
 'ASPLAGMETA-2109',
 'ASPLAGMETA-1572',
 'ASPLAGMETA-1558',
 'ASPLAGMETA-1144',
 'ASPLAGMETA-105',
 'ASPLAGMETA-72',
 'ASPLAGMETA-2126',
 'ASPLAGMETA-2108',
 'ASPLAGMETA-2095',
 'ASPLAGMETA-2012',
 'ASPLAGMETA-1926',
 'ASPLAGMETA-1813',
 'ASPLAGMETA-1672',
 'ASPLAGMETA-1588',
 'ASPLAGMETA-1290',
 'ASPLAGMETA-106',
 'ASPLAGMETA-91',
 'ASPLAGMETA-90',
 'ASPLAGMETA-84',
 'ASPLAGMETA-70',
 'ASPLAGMETA-2107',
 'ASPLAGMETA-1515',
 'ASPLAGMETA-69',
 'ASPLAGMETA-2106',
 'ASPLAGMETA-1487',
 'ASPLAGMETA-65',
 'ASPLAGMETA-2871',
 'ASPLAGMETA-2843',
 'ASPLAGMETA-2801',
 'ASPLAGMETA-2140',
 'ASPLAGMETA-2137',
 'ASPLAGMETA-2136',
 'ASPLAGMETA-2135',
 'ASPLAGMETA-2134',
 'ASPLAGMETA-2133',
 'ASPLAGMETA-2132',
 'ASPLAGMETA-2131',
 'ASPLAGMETA-2129',
 'ASPLAGMETA-2126',
 'ASPLAGMETA-2118',
 'ASPLAGMETA-2117',
 'ASPLAGMETA-2116',
 'ASPLAGMETA-2114',
 'ASPLAGMETA-2108',
 'ASPLAGMETA-2107',
 'ASPLAGMETA-2105',
 'ASPLAGMETA-2104',
 'ASPLAGMETA-2103',
 'ASPLAGMETA-2101',
 'ASPLAGMETA-2100',
 'ASPLAGMETA-2098',
 'ASPLAGMETA-2097',
 'ASPLAGMETA-2081',
 'ASPLAGMETA-1955',
 'ASPLAGMETA-1941',
 'ASPLAGMETA-1912',
 'ASPLAGMETA-1898',
 'ASPLAGMETA-1884',
 'ASPLAGMETA-1869',
 'ASPLAGMETA-1855',
 'ASPLAGMETA-1841',
 'ASPLAGMETA-1827',
 'ASPLAGMETA-1799',
 'ASPLAGMETA-1771',
 'ASPLAGMETA-1742',
 'ASPLAGMETA-1714',
 'ASPLAGMETA-1672',
 'ASPLAGMETA-1588',
 'ASPLAGMETA-1529',
 'ASPLAGMETA-1515',
 'ASPLAGMETA-1433',
 'ASPLAGMETA-1432',
 'ASPLAGMETA-1429',
 'ASPLAGMETA-1388',
 'ASPLAGMETA-1360',
 'ASPLAGMETA-1346',
 'ASPLAGMETA-1332',
 'ASPLAGMETA-1318',
 'ASPLAGMETA-1304',
 'ASPLAGMETA-1262',
 'ASPLAGMETA-1248',
 'ASPLAGMETA-1204',
 'ASPLAGMETA-1162',
 'ASPLAGMETA-1130',
 'ASPLAGMETA-1058',
 'ASPLAGMETA-1044',
 'ASPLAGMETA-1016',
 'ASPLAGMETA-1001',
 'ASPLAGMETA-986',
 'ASPLAGMETA-110',
 'ASPLAGMETA-109',
 'ASPLAGMETA-108',
 'ASPLAGMETA-104',
 'ASPLAGMETA-103',
 'ASPLAGMETA-102',
 'ASPLAGMETA-101',
 'ASPLAGMETA-100',
 'ASPLAGMETA-99',
 'ASPLAGMETA-97',
 'ASPLAGMETA-88',
 'ASPLAGMETA-82',
 'ASPLAGMETA-81',
 'ASPLAGMETA-80',
 'ASPLAGMETA-77',
 'ASPLAGMETA-74',
 'ASPLAGMETA-73',
 'ASPLAGMETA-71',
 'ASPLAGMETA-70',
 'ASPLAGMETA-69',
 'ASPLAGMETA-68',
 'ASPLAGMETA-67',
 'ASPLAGMETA-60',
 'ASPLAGMETA-59',
 'ASPLAGMETA-57',
 'ASPLAGMETA-56',
 'ASPLAGMETA-54',
 'ASPLAGMETA-53',
 'ASPLAGMETA-52',
 'ASPLAGMETA-17',
 'ASPLAGMETA-2134',
 'ASPLAGMETA-2107',
 'ASPLAGMETA-2106',
 'ASPLAGMETA-2104',
 'ASPLAGMETA-2103',
 'ASPLAGMETA-2102',
 'ASPLAGMETA-1984',
 'ASPLAGMETA-1970',
 'ASPLAGMETA-1686',
 'ASPLAGMETA-1543',
 'ASPLAGMETA-1529',
 'ASPLAGMETA-1515',
 'ASPLAGMETA-1487',
 'ASPLAGMETA-1433',
 'ASPLAGMETA-1432',
 'ASPLAGMETA-1430',
 'ASPLAGMETA-1402',
 'ASPLAGMETA-1204',
 'ASPLAGMETA-1176',
 'ASPLAGMETA-1073',
 'ASPLAGMETA-1058',
 'ASPLAGMETA-110',
 'ASPLAGMETA-96',
 'ASPLAGMETA-95',
 'ASPLAGMETA-92',
 'ASPLAGMETA-89',
 'ASPLAGMETA-88',
 'ASPLAGMETA-69',
 'ASPLAGMETA-68',
 'ASPLAGMETA-62',
 'ASPLAGMETA-61',
 'ASPLAGMETA-57',
 'ASPLAGMETA-56',
 'ASPLAGMETA-55',
 'ASPLAGMETA-52',
 'ASPLAGMETA-2141',
 'ASPLAGMETA-2139',
 'ASPLAGMETA-2131',
 'ASPLAGMETA-2128',
 'ASPLAGMETA-2110',
 'ASPLAGMETA-2109',
 'ASPLAGMETA-2103',
 'ASPLAGMETA-2102',
 'ASPLAGMETA-1998',
 'ASPLAGMETA-1785',
 'ASPLAGMETA-1686',
 'ASPLAGMETA-1644',
 'ASPLAGMETA-1572',
 'ASPLAGMETA-1432',
 'ASPLAGMETA-1430',
 'ASPLAGMETA-1388',
 'ASPLAGMETA-1346',
 'ASPLAGMETA-1262',
 'ASPLAGMETA-1190',
 'ASPLAGMETA-1176',
 'ASPLAGMETA-1162',
 'ASPLAGMETA-1073',
 'ASPLAGMETA-1030',
 'ASPLAGMETA-1016',
 'ASPLAGMETA-112',
 'ASPLAGMETA-109',
 'ASPLAGMETA-108',
 'ASPLAGMETA-107',
 'ASPLAGMETA-99',
 'ASPLAGMETA-98',
 'ASPLAGMETA-97',
 'ASPLAGMETA-94',
 'ASPLAGMETA-83',
 'ASPLAGMETA-78',
 'ASPLAGMETA-73',
 'ASPLAGMETA-72',
 'ASPLAGMETA-65',
 'ASPLAGMETA-64',
 'ASPLAGMETA-63',
 'ASPLAGMETA-56',
 'ASPLAGMETA-55',
 'ASPLAGMETA-51',
 'ASPLAGMETA-9',
 'ASPLAGMETA-5',
 'ASPLAGMETA-2127',
 'ASPLAGMETA-2124',
 'ASPLAGMETA-2121',
 'ASPLAGMETA-2109',
 'ASPLAGMETA-2102',
 'ASPLAGMETA-2101',
 'ASPLAGMETA-2053',
 'ASPLAGMETA-1955',
 'ASPLAGMETA-1686',
 'ASPLAGMETA-1574',
 'ASPLAGMETA-1573',
 'ASPLAGMETA-1572',
 'ASPLAGMETA-1558',
 'ASPLAGMETA-1430',
 'ASPLAGMETA-1374',
 'ASPLAGMETA-1205',
 'ASPLAGMETA-1044',
 'ASPLAGMETA-1001',
 'ASPLAGMETA-111',
 'ASPLAGMETA-90',
 'ASPLAGMETA-86',
 'ASPLAGMETA-85',
 'ASPLAGMETA-72',
 'ASPLAGMETA-67',
 'ASPLAGMETA-66',
 'ASPLAGMETA-60',
 'ASPLAGMETA-58',
 'ASPLAGMETA-55',
 'ASPLAGMETA-9',
 'ASPLAGMETA-8',
 'ASPLAGMETA-2871',
 'ASPLAGMETA-2843',
 'ASPLAGMETA-2801',
 'ASPLAGMETA-2140',
 'ASPLAGMETA-2137',
 'ASPLAGMETA-2136',
 'ASPLAGMETA-2135',
 'ASPLAGMETA-2133',
 'ASPLAGMETA-2132',
 'ASPLAGMETA-2131',
 'ASPLAGMETA-2129',
 'ASPLAGMETA-2126',
 'ASPLAGMETA-2117',
 'ASPLAGMETA-2116',
 'ASPLAGMETA-2114',
 'ASPLAGMETA-2108',
 'ASPLAGMETA-2107',
 'ASPLAGMETA-2103',
 'ASPLAGMETA-2101',
 'ASPLAGMETA-2100',
 'ASPLAGMETA-2081',
 'ASPLAGMETA-1941',
 'ASPLAGMETA-1912',
 'ASPLAGMETA-1898',
 'ASPLAGMETA-1884',
 'ASPLAGMETA-1869',
 'ASPLAGMETA-1855',
 'ASPLAGMETA-1841',
 'ASPLAGMETA-1827',
 'ASPLAGMETA-1799',
 'ASPLAGMETA-1771',
 'ASPLAGMETA-1742',
 'ASPLAGMETA-1714',
 'ASPLAGMETA-1672',
 'ASPLAGMETA-1588',
 'ASPLAGMETA-1529',
 'ASPLAGMETA-1515',
 'ASPLAGMETA-1432',
 'ASPLAGMETA-1388',
 'ASPLAGMETA-1360',
 'ASPLAGMETA-1346',
 'ASPLAGMETA-1332',
 'ASPLAGMETA-1318',
 'ASPLAGMETA-1304',
 'ASPLAGMETA-1262',
 'ASPLAGMETA-1248',
 'ASPLAGMETA-1162',
 'ASPLAGMETA-1130',
 'ASPLAGMETA-1016',
 'ASPLAGMETA-986',
 'ASPLAGMETA-110',
 'ASPLAGMETA-109',
 'ASPLAGMETA-108',
 'ASPLAGMETA-103',
 'ASPLAGMETA-102',
 'ASPLAGMETA-101',
 'ASPLAGMETA-100',
 'ASPLAGMETA-99',
 'ASPLAGMETA-97',
 'ASPLAGMETA-88',
 'ASPLAGMETA-81',
 'ASPLAGMETA-80',
 'ASPLAGMETA-77',
 'ASPLAGMETA-74',
 'ASPLAGMETA-73',
 'ASPLAGMETA-71',
 'ASPLAGMETA-70',
 'ASPLAGMETA-69',
 'ASPLAGMETA-68',
 'ASPLAGMETA-67',
 'ASPLAGMETA-59',
 'ASPLAGMETA-56',
 'ASPLAGMETA-53',
 'ASPLAGMETA-17',
 'ASPLAGMETA-2100',
 'ASPLAGMETA-2099',
 'ASPLAGMETA-2098',
 'ASPLAGMETA-2097',
 'ASPLAGMETA-2096',
 'ASPLAGMETA-1462',
 'ASPLAGMETA-2095',
 'ASPLAGMETA-2012']

In [36]:
import pandas as pd

# 1. Carregue apenas o necessário. 
# Removi META_ID e Nº_Meta pois você os descarta no seu código original.
colunas_leitura = ['Chave', 'Resumo', 'Data de Apuração', 'Ano da Meta', 'Valor da Meta', 'Valor Apurado']

df = pd.read_excel(
    r'..\exports\dados_detalhados_metas_2025.xlsx', 
    usecols=colunas_leitura
)

# 2. Extração direta (expand=False retorna Series, permitindo encadeamento)
df['Meta'] = df['Resumo'].str.extract(r'(TJMG\s+\d+)', expand=False).str.strip()

# 3. Reorganização final sem duplicatas e sem .copy() desnecessário
# Removi as repetições de 'Meta' e 'Ano da Meta' que estavam no seu código
cols_finais = ['Meta', 'Chave', 'Ano da Meta', 'Data de Apuração', 'Valor da Meta', 'Valor Apurado']
metas_ano_proc = df[cols_finais]

# 4. Saída
chaves_list = metas_ano_proc['Chave'].tolist()

In [37]:
metas_ano_proc[metas_ano_proc['Chave'] == 'ASPLAGMETA-2102']

,Meta,Chave,Ano da Meta,Data de Apuração,Valor da Meta,Valor Apurado
215,TJMG 5,ASPLAGMETA-2102,2025,NaN,70,NaN
252,TJMG 5,ASPLAGMETA-2102,2025,NaN,70,NaN
293,TJMG 5,ASPLAGMETA-2102,2025,NaN,70,NaN

In [38]:
final = pd.read_excel(r'..\exports\dados_apuracao_final_2025.xlsx')
final['Meta'] = final['Resumo'].str.extract(r'(TJMG\s+\d+)', expand=False).str.strip()
final.columns
final_copy = final[['META_ID', 'Meta', 'Nº_Meta', 'Chave', 'Resumo', 'Valor Apurado', 'Valor da Meta']]
final_copy[final_copy['Meta'] == 'TJMG 5']

,META_ID,Meta,Nº_Meta,Chave,Resumo,Valor Apurado,Valor da Meta
140,ASPLAGMETA-2102,TJMG 5,"TJMG 5 - Realizar, em 2025, 70% (setenta por c...",ASPLAGMETA-2313,"Apuração: TJMG 5 - Realizar, em 2025, 70% (set...",65,70
145,ASPLAGMETA-1430,TJMG 5,"TJMG 5 - Realizar, em 2024, 70% (setenta por c...",ASPLAGMETA-1446,"Apuração: TJMG 5 - Realizar, em 2024, 70% (set...",64,70
176,ASPLAGMETA-55,TJMG 5,"TJMG 5 - Julgar, em 2023, 70% dos processos em...",ASPLAGMETA-342,"Apuração: TJMG 5 - Julgar, em 2023, 70% dos pr...","64,6",70

In [39]:
final_copy = final_copy.merge(metas_ano_proc[['Chave', 'Ano da Meta']], left_on='META_ID', right_on='Chave', how='left')

In [40]:
final_copy[final_copy['Meta'] == 'TJMG 5']

,META_ID,Meta,Nº_Meta,Chave_x,Resumo,Valor Apurado,Valor da Meta,Chave_y,Ano da Meta
321,ASPLAGMETA-2102,TJMG 5,"TJMG 5 - Realizar, em 2025, 70% (setenta por c...",ASPLAGMETA-2313,"Apuração: TJMG 5 - Realizar, em 2025, 70% (set...",65,70,ASPLAGMETA-2102,2025
322,ASPLAGMETA-2102,TJMG 5,"TJMG 5 - Realizar, em 2025, 70% (setenta por c...",ASPLAGMETA-2313,"Apuração: TJMG 5 - Realizar, em 2025, 70% (set...",65,70,ASPLAGMETA-2102,2025
323,ASPLAGMETA-2102,TJMG 5,"TJMG 5 - Realizar, em 2025, 70% (setenta por c...",ASPLAGMETA-2313,"Apuração: TJMG 5 - Realizar, em 2025, 70% (set...",65,70,ASPLAGMETA-2102,2025
330,ASPLAGMETA-1430,TJMG 5,"TJMG 5 - Realizar, em 2024, 70% (setenta por c...",ASPLAGMETA-1446,"Apuração: TJMG 5 - Realizar, em 2024, 70% (set...",64,70,ASPLAGMETA-1430,2024
331,ASPLAGMETA-1430,TJMG 5,"TJMG 5 - Realizar, em 2024, 70% (setenta por c...",ASPLAGMETA-1446,"Apuração: TJMG 5 - Realizar, em 2024, 70% (set...",64,70,ASPLAGMETA-1430,2024
332,ASPLAGMETA-1430,TJMG 5,"TJMG 5 - Realizar, em 2024, 70% (setenta por c...",ASPLAGMETA-1446,"Apuração: TJMG 5 - Realizar, em 2024, 70% (set...",64,70,ASPLAGMETA-1430,2024
383,ASPLAGMETA-55,TJMG 5,"TJMG 5 - Julgar, em 2023, 70% dos processos em...",ASPLAGMETA-342,"Apuração: TJMG 5 - Julgar, em 2023, 70% dos pr...","64,6",70,ASPLAGMETA-55,2023
384,ASPLAGMETA-55,TJMG 5,"TJMG 5 - Julgar, em 2023, 70% dos processos em...",ASPLAGMETA-342,"Apuração: TJMG 5 - Julgar, em 2023, 70% dos pr...","64,6",70,ASPLAGMETA-55,2023
385,ASPLAGMETA-55,TJMG 5,"TJMG 5 - Julgar, em 2023, 70% dos processos em...",ASPLAGMETA-342,"Apuração: TJMG 5 - Julgar, em 2023, 70% dos pr...","64,6",70,ASPLAGMETA-55,2023

In [41]:
final_copy.drop(columns=['Chave_y'], inplace=True)
final_copy.rename(columns={'Chave_x':"Chave"},inplace=True)

In [42]:
final_copy.sort_values(by='Meta', inplace=True)
final_copy

,META_ID,Meta,Nº_Meta,Chave,Resumo,Valor Apurado,Valor da Meta,Ano da Meta
400,ASPLAGMETA-8,TJMG 1,TJMG 1b - Beneficiar 500.000 pessoas com proje...,ASPLAGMETA-155,Apuração: TJMG 1b - Beneficiar 500.000 pessoas...,873.326,500.000,2023
356,ASPLAGMETA-17,TJMG 1,TJMG 1c - (CANCELADA) Beneficiar 100 mães com ...,ASPLAGMETA-168,Apuração: TJMG 1c - (CANCELADA) Beneficiar 100...,33,100,2023
357,ASPLAGMETA-17,TJMG 1,TJMG 1c - (CANCELADA) Beneficiar 100 mães com ...,ASPLAGMETA-168,Apuração: TJMG 1c - (CANCELADA) Beneficiar 100...,33,100,2023
371,ASPLAGMETA-1073,TJMG 1,"TJMG 1a - Beneficiar 6.726 (seis mil, setecent...",ASPLAGMETA-1087,Apuração: TJMG 1a - Beneficiar 6.726 (seis mil...,7.698,6.726,2024
372,ASPLAGMETA-1030,TJMG 1,TJMG 1f - Beneficiar 600 crianças no Estado de...,ASPLAGMETA-1043,Apuração: TJMG 1f - Beneficiar 600 crianças no...,2.217,600,2024
...,...,...,...,...,...,...,...,...
169,ASPLAGMETA-2122,TJMG 97,"TJMG 97 - Aumentar, em 2025, uma média de pelo...",ASPLAGMETA-2155,"Apuração: TJMG 97 - Aumentar, em 2025, uma méd...","30,81",1,2025
380,ASPLAGMETA-83,TJMG 99,TJMG 99 - Decidir todos os recursos excepciona...,ASPLAGMETA-427,Apuração: TJMG 99 - Decidir todos os recursos ...,100,100,2023
291,ASPLAGMETA-1262,TJMG 99,TJMG 99 - Decidir 100% dos recursos excepciona...,ASPLAGMETA-1275,Apuração: TJMG 99 - Decidir 100% dos recursos ...,"67,9",100,2024
292,ASPLAGMETA-1262,TJMG 99,TJMG 99 - Decidir 100% dos recursos excepciona...,ASPLAGMETA-1275,Apuração: TJMG 99 - Decidir 100% dos recursos ...,"67,9",100,2024
290,ASPLAGMETA-1262,TJMG 99,TJMG 99 - Decidir 100% dos recursos excepciona...,ASPLAGMETA-1275,Apuração: TJMG 99 - Decidir 100% dos recursos ...,"67,9",100,2024

In [43]:
final_copy.drop_duplicates(subset=['Chave'], inplace=True)
final_copy['meta_num'] = final_copy['Meta'].str.extract('(\d+)').astype(int)
final_copy = final_copy[final_copy['Meta'].isin(metas_ano_final)].sort_values(by=['meta_num', 'Ano da Meta'])
final_copy = final_copy.drop(columns=['meta_num'])

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\P0165559\AppData\Local\Temp\ipykernel_16656\3819801915.py:2: SyntaxWarning: invalid escape sequence '\d'
  final_copy['meta_num'] = final_copy['Meta'].str.extract('(\d+)').astype(int)

In [44]:
final_copy

,META_ID,Meta,Nº_Meta,Chave,Resumo,Valor Apurado,Valor da Meta,Ano da Meta
384,ASPLAGMETA-55,TJMG 5,"TJMG 5 - Julgar, em 2023, 70% dos processos em...",ASPLAGMETA-342,"Apuração: TJMG 5 - Julgar, em 2023, 70% dos pr...","64,6",70,2023
332,ASPLAGMETA-1430,TJMG 5,"TJMG 5 - Realizar, em 2024, 70% (setenta por c...",ASPLAGMETA-1446,"Apuração: TJMG 5 - Realizar, em 2024, 70% (set...",64,70,2024
321,ASPLAGMETA-2102,TJMG 5,"TJMG 5 - Realizar, em 2025, 70% (setenta por c...",ASPLAGMETA-2313,"Apuração: TJMG 5 - Realizar, em 2025, 70% (set...",65,70,2025
361,ASPLAGMETA-56,TJMG 6,"TJMG 6 - Julgar, em 2023, 70% dos processos em...",ASPLAGMETA-125,"Apuração: TJMG 6 - Julgar, em 2023, 70% dos pr...","61,1",70,2023
272,ASPLAGMETA-1432,TJMG 6,"TJMG 6 - Realizar, em 2024, 70% (setenta por c...",ASPLAGMETA-1459,"Apuração: TJMG 6 - Realizar, em 2024, 70% (set...",63,70,2024
...,...,...,...,...,...,...,...,...
6,ASPLAGMETA-2843,TJMG 152,"TJMG 152 - Elaborar, em 2025, o Plano inicial ...",ASPLAGMETA-2856,"Apuração: TJMG 152 - Elaborar, em 2025, o Plan...",100,100,2025
3,ASPLAGMETA-2857,TJMG 153,TJMG 153 - Ofertar pelo menos 04 (quatro) turm...,ASPLAGMETA-2870,Apuração: TJMG 153 - Ofertar pelo menos 04 (qu...,12,9,2025
0,ASPLAGMETA-2871,TJMG 154,"TJMG 154 – Definir e preparar, até dezembro de...",ASPLAGMETA-2884,"Apuração: TJMG 154 – Definir e preparar, até d...",100,100,2025
12,ASPLAGMETA-2787,TJMG 155,TJMG 155 – Concluir o estudo Diagnóstico dos ...,ASPLAGMETA-2800,Apuração: TJMG 155 – Concluir o estudo Diagnó...,39,39,2025
13,ASPLAGMETA-2773,TJMG 156,TJMG 156 - Implantar o eproc em 84 (oitenta e ...,ASPLAGMETA-2786,Apuração: TJMG 156 - Implantar o eproc em 84 (...,84,84,2025

In [45]:
dados_tjmg_2022 = [
    {"meta": 5, "ano": 2022, "resultado": "60%"}, # [cite: 3]
    {"meta": 6, "ano": 2022, "resultado": "57%"}, # [cite: 6]
    {"meta": 7, "ano": 2022, "resultado": "96%"}, # [cite: 9]
    {"meta": 8, "ano": 2022, "resultado": "30%"}, # [cite: 12]
    {"meta": 9, "ano": 2022, "resultado": "10%"}, # [cite: 15]
    {"meta": 11, "ano": 2022, "resultado": "68%"}, # [cite: 22]
    {"meta": 12, "ano": 2022, "resultado": "68%"}, # [cite: 26]
    {"meta": 13, "ano": 2022, "resultado": "71%"}, # [cite: 30]
    {"meta": 17, "ano": 2022, "resultado": "72%"}, # [cite: 34]
    {"meta": 23, "ano": 2022, "resultado": "74%"}, # [cite: 36]
    {"meta": 29, "ano": 2022, "resultado": "66,1%"}, # [cite: 41]
    {"meta": 31, "ano": 2022, "resultado": "100%"}, # [cite: 43]
    {"meta": 32, "ano": 2022, "resultado": "76%"}, # [cite: 45]
    {"meta": 40, "ano": 2022, "resultado": "43 unidades"}, # [cite: 47]
    {"meta": 42, "ano": 2022, "resultado": "74%"}, # [cite: 50]
    {"meta": 44, "ano": 2022, "resultado": "85%"}, # [cite: 53]
    {"meta": 46, "ano": 2022, "resultado": "75%"}, # [cite: 56]
    {"meta": 48, "ano": 2022, "resultado": "87%"}, # [cite: 58]
    {"meta": 54, "ano": 2022, "resultado": "86%"}, # [cite: 60]
    {"meta": 59, "ano": 2022, "resultado": "92,0%"}, # [cite: 63]
    {"meta": 62, "ano": 2022, "resultado": "100%"}, # [cite: 66]
    {"meta": 64, "ano": 2022, "resultado": "100%"}, # [cite: 69]
    {"meta": 66, "ano": 2022, "resultado": "30,8%"}, # [cite: 71]
    {"meta": 67, "ano": 2022, "resultado": "35%"}, # [cite: 74]
    {"meta": 69, "ano": 2022, "resultado": "25%"}, # [cite: 77]
    {"meta": 77, "ano": 2022, "resultado": "26,3%"} # [cite: 80]
]

In [46]:
dados_tjmg_2022 = pd.DataFrame(dados_tjmg_2022)
dados_tjmg_2022

    meta   ano    resultado
0      5  2022          60%
1      6  2022          57%
2      7  2022          96%
3      8  2022          30%
4      9  2022          10%
5     11  2022          68%
6     12  2022          68%
7     13  2022          71%
8     17  2022          72%
9     23  2022          74%
10    29  2022        66,1%
11    31  2022         100%
12    32  2022          76%
13    40  2022  43 unidades
14    42  2022          74%
15    44  2022          85%
16    46  2022          75%
17    48  2022          87%
18    54  2022          86%
19    59  2022        92,0%
20    62  2022         100%
21    64  2022         100%
22    66  2022        30,8%
23    67  2022          35%
24    69  2022          25%
25    77  2022        26,3%

In [47]:
dados_tjmg_2022['meta_x'] = dados_tjmg_2022['meta'].apply(lambda x: f'TJMG {x}')
dados_tjmg_2022.drop(columns=['meta'], inplace=True)
dados_tjmg_2022.rename(columns={'meta_x': 'Meta'}, inplace=True)
dados_tjmg_2022 = dados_tjmg_2022[dados_tjmg_2022['Meta'].isin(metas_ano_final)].copy()
dados_tjmg_2022.reset_index(drop=True, inplace=True)

In [48]:
dados_tjmg_2022.iloc[5, 1] = 43
dados_tjmg_2022

    ano resultado     Meta
0  2022       60%   TJMG 5
1  2022       57%   TJMG 6
2  2022       96%   TJMG 7
3  2022       72%  TJMG 17
4  2022     66,1%  TJMG 29
5  2022        43  TJMG 40
6  2022     92,0%  TJMG 59
7  2022      100%  TJMG 62
8  2022       35%  TJMG 67
9  2022       25%  TJMG 69

In [49]:
# 1. Renomear colunas para coincidir com o df1
dados_tjmg_2022 = dados_tjmg_2022.rename(columns={'ano': 'Ano da Meta', 'resultado': 'Valor Apurado'})

# 2. Limpar a coluna 'Valor Apurado' (remover %, trocar vírgula por ponto)
dados_tjmg_2022['Valor Apurado'] = (
    dados_tjmg_2022['Valor Apurado']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.replace(',', '.', regex=False)
    .astype(float)
)

In [50]:
# Criar um mapeamento das colunas fixas a partir do df1
# Pegamos a primeira ocorrência de cada Meta para servir de referência
referencia = final_copy.groupby('Meta')[['META_ID', 'Chave', 'Resumo']].first().reset_index()

# Mesclar essas informações no df2
dados_tjmg_2022 = dados_tjmg_2022.merge(referencia, on='Meta', how='left')

# Concatenar os dois
df_final = pd.concat([final_copy, dados_tjmg_2022], ignore_index=True)
df_final['meta_num'] = df_final['Meta'].str.extract('(\d+)').astype(int)
df_final = df_final[df_final['Meta'].isin(metas_ano_final)].sort_values(by=['meta_num', 'Ano da Meta'])
df_final = df_final.drop(columns=['meta_num'])
df_final

<>:10: SyntaxWarning: invalid escape sequence '\d'
<>:10: SyntaxWarning: invalid escape sequence '\d'
C:\Users\P0165559\AppData\Local\Temp\ipykernel_16656\3963402628.py:10: SyntaxWarning: invalid escape sequence '\d'
  df_final['meta_num'] = df_final['Meta'].str.extract('(\d+)').astype(int)

,META_ID,Meta,Nº_Meta,Chave,Resumo,Valor Apurado,Valor da Meta,Ano da Meta
102,ASPLAGMETA-55,TJMG 5,NaN,ASPLAGMETA-342,"Apuração: TJMG 5 - Julgar, em 2023, 70% dos pr...",60.0,NaN,2022
0,ASPLAGMETA-55,TJMG 5,"TJMG 5 - Julgar, em 2023, 70% dos processos em...",ASPLAGMETA-342,"Apuração: TJMG 5 - Julgar, em 2023, 70% dos pr...","64,6",70,2023
1,ASPLAGMETA-1430,TJMG 5,"TJMG 5 - Realizar, em 2024, 70% (setenta por c...",ASPLAGMETA-1446,"Apuração: TJMG 5 - Realizar, em 2024, 70% (set...",64,70,2024
2,ASPLAGMETA-2102,TJMG 5,"TJMG 5 - Realizar, em 2025, 70% (setenta por c...",ASPLAGMETA-2313,"Apuração: TJMG 5 - Realizar, em 2025, 70% (set...",65,70,2025
103,ASPLAGMETA-56,TJMG 6,NaN,ASPLAGMETA-125,"Apuração: TJMG 6 - Julgar, em 2023, 70% dos pr...",57.0,NaN,2022
...,...,...,...,...,...,...,...,...
97,ASPLAGMETA-2843,TJMG 152,"TJMG 152 - Elaborar, em 2025, o Plano inicial ...",ASPLAGMETA-2856,"Apuração: TJMG 152 - Elaborar, em 2025, o Plan...",100,100,2025
98,ASPLAGMETA-2857,TJMG 153,TJMG 153 - Ofertar pelo menos 04 (quatro) turm...,ASPLAGMETA-2870,Apuração: TJMG 153 - Ofertar pelo menos 04 (qu...,12,9,2025
99,ASPLAGMETA-2871,TJMG 154,"TJMG 154 – Definir e preparar, até dezembro de...",ASPLAGMETA-2884,"Apuração: TJMG 154 – Definir e preparar, até d...",100,100,2025
100,ASPLAGMETA-2787,TJMG 155,TJMG 155 – Concluir o estudo Diagnóstico dos ...,ASPLAGMETA-2800,Apuração: TJMG 155 – Concluir o estudo Diagnó...,39,39,2025
101,ASPLAGMETA-2773,TJMG 156,TJMG 156 - Implantar o eproc em 84 (oitenta e ...,ASPLAGMETA-2786,Apuração: TJMG 156 - Implantar o eproc em 84 (...,84,84,2025

In [51]:
df_textos_meta_final = df_final[df_final['Ano da Meta'] == 2025][['Meta', 'Nº_Meta', 'Ano da Meta', 'Valor da Meta']]
df_textos_meta_final

,Meta,Nº_Meta,Ano da Meta,Valor da Meta
2,TJMG 5,"TJMG 5 - Realizar, em 2025, 70% (setenta por c...",2025,70
5,TJMG 6,"TJMG 6 - Realizar, em 2025, 70% (setenta por c...",2025,70
8,TJMG 7,"TJMG 7 - Publicar, em 2025, 95% (noventa e cin...",2025,95
11,TJMG 10,"TJMG 10 - Reduzir, até 31/12/2025, em 12% (tri...",2025,12
14,TJMG 17,"TJMG 17 - Executar, até dezembro de 2025, 70% ...",2025,70
17,TJMG 29,"TJMG 29 - Julgar, em 2025, em até 100 (cem) di...",2025,80
20,TJMG 40,TJMG 40 - Implantar o Desdobramento do Planeja...,2025,30
23,TJMG 59,"TJMG 59 - Julgar, até 31/12/2025, 85% (oitenta...",2025,85
26,TJMG 62,"TJMG 62 - Cumprir, até dezembro de 2025, 100% ...",2025,100
29,TJMG 67,"TJMG 67 - Cumprir, até o final de 2025, 94% (n...",2025,94
32,TJMG 69,"TJMG 69 - Cumprir, até 31/12/2025, 90% (novent...",2025,90
35,TJMG 79,"TJMG 79 - Executar, até 2025, 100% (cem por ce...",2025,100
38,TJMG 80,"TJMG 80 - Concluir, até dezembro de 2025, 100%...",2025,100
41,TJMG 85,"TJMG 85 - Proferir, em 2025, 60.000 (sessenta ...",2025,60.000
44,TJMG 91,TJMG 91 - Movimentar 95% (noventa e cinco por ...,2025,95
47,TJMG 95,"TJMG 95 - Executar, no ano de 2025, 100% (cem ...",2025,100
50,TJMG 96,"TJMG 96 - Executar, em 2025, 100% (cem por cen...",2025,100
53,TJMG 97,"TJMG 97 - Aumentar, em 2025, uma média de pelo...",2025,1
56,TJMG 100,"TJMG 100 - Promover, por ação própria ou media...",2025,50
59,TJMG 104,"TJMG 104 - Executar, em 2025, 100% (cem por ce...",2025,100
61,TJMG 109,"TJMG 109 - Emitir, até 31/12/2025, Termo de Au...",2025,70
63,TJMG 111,"TJMG 111 - Executar, até dezembro de 2025, 80%...",2025,80
65,TJMG 115,TJMG 115 - Devolver para o respectivo Cartório...,2025,95
67,TJMG 123,TJMG 123 - Concluir 100% (cem por cento) das e...,2025,100
69,TJMG 124,TJMG 124 - Alcançar 20.000 (vinte mil) pessoas...,2025,20.000
71,TJMG 126,TJMG 126 - Realizar 100% (cem por cento) das e...,2025,100
72,TJMG 128,TJMG 128 - Cessar a competência delegada nas a...,2025,40
73,TJMG 129,TJMG 129 - Executar 100% (cem por cento) do pr...,2025,100
74,TJMG 129,TJMG 129 - Executar 100% (cem por cento) das e...,2025,100
75,TJMG 130,TJMG 130 - Implantar a Central de Processos El...,2025,13
76,TJMG 131,TJMG 131 - Executar 100% (cem por cento) das e...,2025,100
77,TJMG 132,"TJMG 132 - Executar, em 2025, 100% (cem por ce...",2025,100
78,TJMG 133,"TJMG 133 - Instalar, em 2025, o eproc nas unid...",2025,100
79,TJMG 134,"TJMG 134 - Julgar, em 2025, 60% (sessenta por ...",2025,60
80,TJMG 135,"TJMG 135 - Exercer, em 2025, o juízo de admiss...",2025,100
81,TJMG 136,"TJMG 136 - Colocar, pelo menos, 1 (um) Mínimo ...",2025,1
82,TJMG 137,"TJMG 137 - Concluir, até 19/12/2025, 40% do pr...",2025,40
83,TJMG 138,"TJMG 138 - Promover, em 2025, um atendimento d...",2025,1.200
84,TJMG 139,TJMG 139 - Implementar ao menos 5 (cinco) proj...,2025,5
85,TJMG 140,TJMG 140 - Realizar ao menos 25 (vinte e cinco...,2025,25
86,TJMG 141,"TJMG 141 - Virtualizar, em 2025, o acervo físi...",2025,100
87,TJMG 142,TJMG 142 - Expandir o PJE para a classe inquér...,2025,100
88,TJMG 143,"TJMG 143 - Aumentar, até 18/12/2025, em pelo m...",2025,10
89,TJMG 144,"TJMG 144 - Obter, até 18/12/2025, pelo menos 1...",2025,10
90,TJMG 145,"TJMG 145 - Beneficiar, até 18/12/2025, pelo me...",2025,250.000
91,TJMG 146,"TJMG 146 - Reduzir, até 31/12/2025, em 10% (de...",2025,10
92,TJMG 147,"TJMG 147 - Reduzir, até 31/12/2025, em 30% (de...",2025,30
93,TJMG 148,"TJMG 148 - Reduzir, até 31/12/2025, em 4% (qua...",2025,4
94,TJMG 149,"TJMG 149 - Reduzir, até 31/12/2025, 50% (cinqu...",2025,50
95,TJMG 150,"TJMG 150 – Garantir, no ano de 2025, a reserva...",2025,1
96,TJMG 151,"TJMG 151 – Publicar, no Portal TJMG, 2 (dois) ...",2025,2
97,TJMG 152,"TJMG 152 - Elaborar, em 2025, o Plano inicial ...",2025,100
98,TJMG 153,TJMG 153 - Ofertar pelo menos 04 (quatro) turm...,2025,9
99,TJMG 154,"TJMG 154 – Definir e preparar, até dezembro de...",2025,100
100,TJMG 155,TJMG 155 – Concluir o estudo Diagnóstico dos ...,2025,39
101,TJMG 156,TJMG 156 - Implantar o eproc em 84 (oitenta e ...,2025,84

In [52]:
df_textos_meta_final_tabela = df_final[['Meta', 'Valor Apurado', 'Ano da Meta']]
df_textos_meta_final_tabela

# 1. Garantir conversão numérica
df_textos_meta_final_tabela['Valor Apurado'] = (
    df_textos_meta_final_tabela['Valor Apurado']
    .astype(str)
    .str.replace(',', '.')
    .astype(float)
)

# 2. Usar pivot_table em vez de pivot
# aggfunc='first' pega o primeiro valor se houver duplicatas. 
# Se preferir a média, use aggfunc='mean'.
df_pivot = df_textos_meta_final_tabela.pivot_table(
    index='Meta', 
    columns='Ano da Meta', 
    values='Valor Apurado', 
    aggfunc='first' 
)

# 3. Ajustar colunas e índice
df_pivot.columns.name = None
df_pivot = df_pivot.reset_index()
df_pivot.fillna(0, inplace=True)  # Substituir NaN por 0, se necessário
df_pivot['meta_num'] = df_pivot['Meta'].str.extract('(\d+)').astype(int)
df_pivot = df_pivot[df_pivot['Meta'].isin(metas_ano_final)].sort_values(by=['meta_num'])
df_pivot = df_pivot.drop(columns=['meta_num'])
df_pivot.reset_index(drop=True, inplace=True)
df_pivot

<>:26: SyntaxWarning: invalid escape sequence '\d'
<>:26: SyntaxWarning: invalid escape sequence '\d'
C:\Users\P0165559\AppData\Local\Temp\ipykernel_16656\3394614411.py:26: SyntaxWarning: invalid escape sequence '\d'
  df_pivot['meta_num'] = df_pivot['Meta'].str.extract('(\d+)').astype(int)
C:\Users\P0165559\AppData\Local\Temp\ipykernel_16656\3394614411.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_textos_meta_final_tabela['Valor Apurado'] = (

        Meta   2022     2023     2024     2025
0     TJMG 5   60.0   64.600   64.000   65.000
1     TJMG 6   57.0   61.100   63.000   67.000
2     TJMG 7   96.0   98.500   99.000   93.660
3    TJMG 10    0.0 -109.190   10.160   65.100
4    TJMG 17   72.0   86.100   24.000   96.000
5    TJMG 29   66.1   76.400   75.000   73.000
6    TJMG 40   43.0   72.000   61.000   32.000
7    TJMG 59   92.0   89.600   98.000   90.000
8    TJMG 62  100.0  100.000  100.000  100.000
9    TJMG 67   35.0   58.000   65.600   85.000
10   TJMG 69   25.0   56.200   92.900  100.000
11   TJMG 79    0.0   30.000   45.000   45.500
12   TJMG 80    0.0   85.700   91.000   83.300
13   TJMG 85    0.0   77.962   71.878   87.609
14   TJMG 91    0.0   97.900  100.000  103.000
15   TJMG 95    0.0   67.000   89.000   50.000
16   TJMG 96    0.0   77.000   93.000   93.000
17   TJMG 97    0.0    5.210  -13.260   30.810
18  TJMG 100    0.0   55.000   32.000   97.000
19  TJMG 104    0.0   69.200   70.000   68.000
20  TJMG 109    0.0    0.000   48.500   42.400
21  TJMG 111    0.0    0.000   87.500   87.000
22  TJMG 115    0.0    0.000   94.000   94.000
23  TJMG 123    0.0    0.000   68.000   87.390
24  TJMG 124    0.0    0.000   39.227   55.266
25  TJMG 126    0.0    0.000   52.500   78.700
26  TJMG 128    0.0    0.000    0.000   64.000
27  TJMG 129    0.0    0.000    0.000   64.000
28  TJMG 130    0.0    0.000    0.000   17.000
29  TJMG 131    0.0    0.000    0.000    0.000
30  TJMG 132    0.0    0.000    0.000   95.000
31  TJMG 133    0.0    0.000    0.000  100.000
32  TJMG 134    0.0    0.000    0.000    0.000
33  TJMG 135    0.0    0.000    0.000    0.000
34  TJMG 136    0.0    0.000    0.000    0.000
35  TJMG 137    0.0    0.000    0.000   28.540
36  TJMG 138    0.0    0.000    0.000    2.755
37  TJMG 139    0.0    0.000    0.000    1.000
38  TJMG 140    0.0    0.000    0.000   97.000
39  TJMG 141    0.0    0.000    0.000   83.600
40  TJMG 142    0.0    0.000    0.000  100.000
41  TJMG 143    0.0    0.000    0.000   12.000
42  TJMG 144    0.0    0.000    0.000    2.000
43  TJMG 145    0.0    0.000    0.000  135.419
44  TJMG 146    0.0    0.000    0.000   30.400
45  TJMG 147    0.0    0.000    0.000   21.000
46  TJMG 148    0.0    0.000    0.000   15.100
47  TJMG 149    0.0    0.000    0.000   -9.200
48  TJMG 150    0.0    0.000    0.000    1.000
49  TJMG 151    0.0    0.000    0.000    2.000
50  TJMG 152    0.0    0.000    0.000  100.000
51  TJMG 153    0.0    0.000    0.000   12.000
52  TJMG 154    0.0    0.000    0.000  100.000
53  TJMG 155    0.0    0.000    0.000   39.000
54  TJMG 156    0.0    0.000    0.000   84.000

In [53]:
with pd.ExcelWriter(r'..\exports\metas_institucionais_2025.xlsx', engine='openpyxl') as writer:
    df_pivot.to_excel(writer, sheet_name='Valores Apurados', index=True)
    df_textos_meta_final.to_excel(writer, sheet_name='Textos Metas', index=True)